name: Build and Push Docker Image

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: master9/test-webpage:latest
        file: Dockerfile

  create-pod:
    name: Create Pod in Cluster
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

    - name: Read namespace
      id: read-namespace
      run: echo "::set-output name=namespace::$(cat ns.txt | cut -d' ' -f2)"

    - name: Check if namespace exists
      id: check-namespace
      run: |
        if kubectl get namespace ${{ steps.read-namespace.outputs.namespace }}; then
          echo "Namespace exists"
          echo "::set-output name=exists::true"
        else
          echo "Namespace does not exist"
          echo "::set-output name=exists::false"
        fi

    - name: Clone namespace repository
      if: steps.check-namespace.outputs.exists == 'false'
      uses: actions/checkout@v2
      with:
        repository: Devops1904/aws-eks-test-cluster1
        path: aws-eks-test-cluster1
        token: ${{ secrets.MYGITHUB_TOKEN }}

    - name: Append namespace to namespaces.txt
      if: steps.check-namespace.outputs.exists == 'false'
      run: python3 scripts/append_namespace.py ${{ steps.read-namespace.outputs.namespace }}

    - name: Commit and push changes
      if: steps.check-namespace.outputs.exists == 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
      run: |
        echo GITHUB_TOKEN
        cd aws-eks-test-cluster1
        git config --global user.name "santosh09"
        git config --global user.email "santosh09@gmail.com"
        git add namespaces.txt
        git commit -m "Add namespace ${{ steps.read-namespace.outputs.namespace }}"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/Devops1904/aws-eks-test-cluster1.git

    - name: Wait for namespace creation
      if: steps.check-namespace.outputs.exists == 'false'
      run: sleep 60

    - name: Check if deployment exists
      id: check-deployment
      run: |
        if kubectl get deployment test-webpage-deployment -n ${{ steps.read-namespace.outputs.namespace }}; then
          echo "Deployment exists"
          echo "::set-output name=exists::true"
        else
          echo "Deployment does not exist"
          echo "::set-output name=exists::false"
        fi

    - name: Delete existing deployment
      if: steps.check-deployment.outputs.exists == 'true'
      run: kubectl delete deployment test-webpage-deployment -n ${{ steps.read-namespace.outputs.namespace }}

    - name: Create Pod
      run: kubectl apply -f pod-definition.yml -n ${{ steps.read-namespace.outputs.namespace }}

    - name: Create Service
      run: kubectl apply -f service.yml -n ${{ steps.read-namespace.outputs.namespace }}

